// models/followUpQuestion.js
module.exports = (sequelize, DataTypes) => {
    const FollowUpQuestion = sequelize.define('FollowUpQuestion', {
      id: {
        type: DataTypes.INTEGER,
        autoIncrement: true,
        primaryKey: true,
        allowNull: false,
      },
      interview_response_id: {
        type: DataTypes.INTEGER,
        references: {
          model: 'InterviewResponses',
          key: 'id',
        },
        allowNull: false,
        onDelete: 'CASCADE',
      },
      question_text: {
        type: DataTypes.TEXT,
        allowNull: false,
      },
      media_url: {
        type: DataTypes.STRING,
        allowNull: true, // Optional field
      },
      created_by: {
        type: DataTypes.STRING,
        allowNull: false,
        defaultValue: 'LLM', // Indicates that the question was generated by the LLM
      },
      createdAt: {
        type: DataTypes.DATE,
        defaultValue: DataTypes.NOW,
        allowNull: false,
      },
      updatedAt: {
        type: DataTypes.DATE,
        defaultValue: DataTypes.NOW,
        allowNull: false,
      },
    }, {
      tableName: 'FollowUpQuestions',
      timestamps: true,
    });
  
    FollowUpQuestion.associate = (models) => {
      FollowUpQuestion.belongsTo(models.InterviewResponse, {
        foreignKey: 'interview_response_id',
        as: 'interview_response',
      });
    };
  
    return FollowUpQuestion;
  };
  