const greenEnergyAssessmentReferenceExamples = {
    "Problem Solving": [
      {
        "interview_question_id": 6,
        "question": "What are the main drivers behind the rapid growth of solar energy in India in recent years? Discuss the technological and economic factors involved.",
        "answers": [
          {
            "score": 5,
            "answer": "The rapid growth of solar energy in India can be attributed to a combination of technological advancements and economic incentives. Technologically, the cost of solar panels has significantly decreased due to improvements in manufacturing and efficiency. Economically, the government has introduced subsidies and incentives such as the National Solar Mission, making solar energy more affordable. Additionally, the increased awareness of environmental sustainability has driven both public and private investments in solar energy projects."
          },
          {
            "score": 4,
            "answer": "The growth of solar energy in India is driven by government subsidies and technological improvements. Solar panels have become cheaper, and the National Solar Mission has provided significant economic incentives. However, the environmental benefits of solar energy are also a key factor in its growth."
          },
          {
            "score": 3,
            "answer": "India’s solar energy has grown due to government support and cheaper solar panels. The National Solar Mission played a role in this, and people are more interested in solar energy because it’s good for the environment."
          },
          {
            "score": 2,
            "answer": "Solar energy is growing because it’s cheaper now and the government supports it. People also like it because it helps the environment."
          },
          {
            "score": 1,
            "answer": "Solar energy is growing in India because it’s getting popular and the government likes it."
          }
        ]
      },
      {
        "interview_question_id": 7,
        "question": "Given that a wind turbine in Tamil Nadu produces an average of 2.5 megawatts of electricity and there are 500 turbines in a wind farm, calculate the total electricity generated by the wind farm in a day if each turbine operates at 75% capacity for 24 hours.",
        "answers": [
          {
            "score": 5,
            "answer": "22,500 MWh"
          },
          {
            "score": 0,
            "answer": "Any answer other that does not include 22,500 MWh"
          }
        ]
      },
      {
        "interview_question_id": 8,
        "question": "Explain how hydropower can be both a sustainable and reliable source of energy for India. What are the potential drawbacks of relying heavily on hydropower in the Indian context?",
        "answers": [
          {
            "score": 5,
            "answer": "Hydropower is sustainable because it uses the natural flow of water, which is a renewable resource. It's reliable because once infrastructure is built, it can generate consistent power. However, relying heavily on hydropower has drawbacks. Seasonal variations in water flow, the environmental impact on aquatic ecosystems, and displacement of local communities due to dam construction are significant concerns."
          },
          {
            "score": 4,
            "answer": "Hydropower is sustainable as it uses water, a renewable resource. It’s reliable because it can consistently generate power. However, it can harm the environment and displace people."
          },
          {
            "score": 3,
            "answer": "Hydropower is good because water is renewable, and it can generate power regularly. But it can cause environmental issues and displace communities."
          },
          {
            "score": 2,
            "answer": "Hydropower is renewable and reliable, but it can harm the environment and people."
          },
          {
            "score": 1,
            "answer": "Hydropower is good, but it can have some bad effects."
          }
        ]
      },
      {
        "interview_question_id": 9,
        "question": "Discuss the economic benefits that renewable energy can bring to local communities in India. Include examples of job creation and cost savings.",
        "answers": [
          {
            "score": 5,
            "answer": "Renewable energy can significantly benefit local communities in India. It creates jobs in manufacturing, installation, and maintenance of renewable energy infrastructure. For example, solar panel production and installation have created thousands of jobs. Additionally, renewable energy reduces electricity costs, benefiting consumers. The decentralization of energy production also reduces transmission losses and empowers rural areas to become self-sufficient."
          },
          {
            "score": 4,
            "answer": "Renewable energy benefits local communities by creating jobs in solar panel installation and maintenance. It also reduces electricity costs, making energy more affordable."
          },
          {
            "score": 3,
            "answer": "Renewable energy creates jobs and makes electricity cheaper for local communities."
          },
          {
            "score": 2,
            "answer": "Renewable energy can create jobs and reduce energy costs for people."
          },
          {
            "score": 1,
            "answer": "Renewable energy helps local communities by saving money and making jobs."
          }
        ]
      },
      {
        "interview_question_id": 10,
        "question": "Imagine you are presenting the benefits of renewable energy to a group of high school students in India. How would you explain the importance of renewable energy in simple terms?",
        "answers": [
          {
            "score": 5,
            "answer": "Renewable energy is important because it uses natural resources like sunlight, wind, and water that won’t run out. Unlike fossil fuels, which can harm our environment, renewable energy is clean and safe. It helps keep our air and water clean and creates jobs in new technologies. Using renewable energy means we’re taking care of our planet for the future."
          },
          {
            "score": 4,
            "answer": "Renewable energy uses resources like sunlight and wind, which are always available. It’s better for the environment and helps reduce pollution."
          },
          {
            "score": 3,
            "answer": "Renewable energy is good because it uses sunlight and wind and doesn’t pollute as much."
          },
          {
            "score": 2,
            "answer": "Renewable energy is clean and uses sunlight and wind."
          },
          {
            "score": 1,
            "answer": "Renewable energy is good because it’s clean and uses natural resources."
          }
        ]
      },
      {
        "interview_question_id": 11,
        "question": "Propose an innovative solution to overcome one of the major challenges facing renewable energy adoption in India today, such as energy storage or grid integration.",
        "answers": [
          {
            "score": 5,
            "answer": "One innovative solution to improve energy storage in India is to invest in large-scale battery storage systems using advanced technologies like lithium-ion or flow batteries. These systems can store excess energy generated during peak production times, which can be used during periods of low production or high demand. Additionally, integrating smart grid technology can optimize energy distribution, reduce losses, and improve the reliability of renewable energy sources."
          },
          {
            "score": 4,
            "answer": "Investing in large-scale battery storage can help store excess energy, which can be used when needed. Smart grids can also improve energy distribution and reduce losses."
          },
          {
            "score": 3,
            "answer": "We can use big batteries to store energy and smart grids to manage it better."
          },
          {
            "score": 2,
            "answer": "Using batteries to store energy can help, and smart grids can make it work better."
          },
          {
            "score": 1,
            "answer": "Batteries and smart grids can help with energy storage."
          }
        ]
      },
      {
        "interview_question_id": 12,
        "question": "Analyze the role of Indian policies in promoting renewable energy. How effective are these policies in driving national change?",
        "answers": [
          {
            "score": 5,
            "answer": "Indian policies have played a crucial role in promoting renewable energy. The National Solar Mission, for example, has set ambitious targets for solar power capacity and provided subsidies to lower costs. Additionally, policies like tax incentives, renewable purchase obligations, and accelerated depreciation have encouraged private investment in renewable energy. These policies have been effective in increasing the share of renewables in India's energy mix, though challenges remain in areas like grid integration and storage."
          },
          {
            "score": 4,
            "answer": "Indian policies like the National Solar Mission have helped promote renewable energy by setting targets and providing subsidies. These policies have increased renewable energy use, but some challenges remain."
          },
          {
            "score": 3,
            "answer": "Policies like the National Solar Mission have promoted renewable energy, but there are still challenges."
          },
          {
            "score": 2,
            "answer": "Indian policies have helped renewable energy, but there are still problems."
          },
          {
            "score": 1,
            "answer": "Indian policies are helping renewable energy, but there are challenges."
          }
        ]
      },
      {
        "interview_question_id": 13,
        "question": "Identify and describe a recent breakthrough in renewable energy technology developed in India. How does this breakthrough contribute to the overall efficiency and adoption of renewable energy?",
        "answers": [
          {
            "score": 5,
            "answer": "A recent breakthrough in renewable energy technology in India is the development of more efficient solar cells using perovskite materials. These materials offer higher energy conversion efficiency than traditional silicon-based cells. This breakthrough not only makes solar power more cost-effective but also accelerates the adoption of solar energy across different regions, particularly in rural areas where cost is a significant barrier."
          },
          {
            "score": 4,
            "answer": "The use of perovskite materials in solar cells is a recent breakthrough in India, making solar energy more efficient and affordable."
          },
          {
            "score": 3,
            "answer": "A recent breakthrough in India involves new materials in solar cells, making them more efficient."
          },
          {
            "score": 2,
            "answer": "New materials in solar cells are a breakthrough in India, improving efficiency."
          },
          {
            "score": 1,
            "answer": "India has had breakthroughs in solar energy technology recently."
          }
        ]
      },
      {
        "interview_question_id": 14,
        "question": "Consider a scenario where a rural community in India relies solely on solar energy. What measures would you implement to ensure a continuous power supply during extended periods of cloudy weather?",
        "answers": [
          {
            "score": 5,
            "answer": "To ensure a continuous power supply during extended periods of cloudy weather, I would implement a combination of energy storage solutions and hybrid energy systems. Large-scale battery storage can store excess energy generated on sunny days, while integrating other renewable sources like wind or small hydropower can provide additional power. Furthermore, energy-efficient appliances and demand-side management can reduce consumption during low production periods."
          },
          {
            "score": 4,
            "answer": "Using battery storage and integrating wind energy with solar power can help ensure a continuous power supply during cloudy weather."
          },
          {
            "score": 3,
            "answer": "Battery storage and using other renewable energy sources can help maintain power during cloudy days."
          },
          {
            "score": 2,
            "answer": "Using batteries and other energy sources can help keep power on during cloudy days."
          },
          {
            "score": 1,
            "answer": "Batteries can help maintain power during cloudy days."
          }
        ]
      },
      {
        "interview_question_id": 15,
        "question": "How would you address the concerns of individuals in India who are skeptical about transitioning to renewable energy? Provide a strategy for effective communication and persuasion.",
        "answers": [
          {
            "score": 5,
            "answer": "To address the concerns of individuals skeptical about transitioning to renewable energy, I would focus on educating them about the long-term economic benefits, such as cost savings on energy bills and job creation in the renewable sector. I would also highlight the environmental and health benefits, emphasizing how renewable energy can reduce pollution and improve public health. Engaging community leaders and using real-life examples of successful renewable projects can also help build trust and acceptance."
          },
          {
            "score": 4,
            "answer": "I would educate people on the economic and environmental benefits of renewable energy, using examples of successful projects to build trust."
          },
          {
            "score": 3,
            "answer": "I would explain the benefits of renewable energy and show examples of its success."
          },
          {
            "score": 2,
            "answer": "I would talk about the benefits of renewable energy to convince people."
          },
          {
            "score": 1,
            "answer": "I would try to explain the benefits of renewable energy."
          }
        ]
      }
    ]
  };
  
  module.exports = { greenEnergyAssessmentReferenceExamples };
  